### PR TITLE
Added sass-embedded and swapped to async compiler api

### PR DESCRIPTION
**Pull request by NathanBeddoeWebDev**
See discussion @ https://github.com/glromeo/esbuild-sass-plugin/issues/160

Also see https://github.com/sass/sass/issues/3296 for background into this issue, and links to proposals and PR's.

### CODE REVIEW

**Comment by glromeo** [comment]
Thank you Nathan
I ran my benchmark (the one in fixtures) and with my rig

my old branch does
built in: 2.450s ..on the first build
then
built in: 176.849ms ...on rebuilding due to a TS change
built in: 173.599ms ...on rebuilding due to a SCSS change

when running it in your branch it does
built in: 734.365ms
then
built in: 236.434ms
built in: 131.038ms
built in: 179.46ms
built in: 177.125ms
...on rebuilding due to a TS change
built in: 1.080s
built in: 1.396s
built in: 998.105ms
...on rebuilding due to a SCSS change

Now... I am pleasantly surpised by the initial build speed improvement 😮  and puzzled 🤔 by the
subsequent being slower when actually caching and having the compiler already initialized should 
deliver opposite results.

For TS changes it's pretty much the same and that makes sense but sass...hmm

I am eager to merge your PR let me get my head around this first, ideally I want to merge once and have
a proper improvement across the board... If I can't find out the issue I will merge anyway because I reckon
the overall experience will be much better!

Good job man!!! 👍

**Comment by glromeo** [comment]
there must have been something going on earlier on because now I get more consistent results
for both TS and SCSS changes

built in: 816.274ms

built in: 181.181ms
built in: 156.739ms
built in: 175.843ms
built in: 151.272ms
built in: 153.187ms
built in: 152.261ms
built in: 156.768ms
built in: 145.372ms

**Comment by NathanBeddoeWebDev** [comment]
Wow, that's quite the increase there on subsequent builds...
I've got a couple examples on my large project while watching. Note: I double checked that the dart.exe wasn't starting on each subsequent save, and it appears to be maintaining the same process.

Old Sass Plugin:
image

Embedded Sass Plugin
image

**Comment by glromeo** [comment]
Yup... I am impressed man! 
Now there are just the tests in the way to merge I am having a look from my end to see if I can help

**Comment by NathanBeddoeWebDev** [comment]
Is coverage failing? Not sure why that'd be, but I'm seeing test results, and then it's hanging instead of showing me test coverage results.

**Comment by glromeo** [comment]
😆 this is not the branch I was benchmarking with
the main branch is good... this branch is very slow (10x)

**Comment by glromeo** [comment]
good news tests are failing (here) mostly because of the embedded using \r in windows...

**Comment by glromeo** [comment]
can you please create another PR from main?

**Comment by glromeo** [comment]
..actually it's better if we fix this branch 😄

**Pull request closed without merging**
