### PR TITLE
Merging Nathan's async changes

### PR DESCRIPTION
**Pull request by glromeo**

### CODE REVIEW

**Comment by NathanBeddoeWebDev** [comment]
Thanks. I've removed the naming changes, and confirmed with benchmark that the performance boost is still there. I'll have to check what I did in my fork branch to cook it that bad.

**Comment by glromeo** [comment]
the init compiler was in the render

**Comment by glromeo** [comment]
now I am going to fix the tests and release another version

**Comment by glromeo** [comment]
@NathanBeddoeWebDev 

image

the compiler needs to be disposed at the end...that's why the tests where hanging

**Comment by glromeo** [comment]
@NathanBeddoeWebDev I am sorry that by making the PR myself you don't show up amongst the contributors
if you want just create a PR for something silly like removing that semicolon at line 78 
or I think I saw an unused import somewhere ...I will be glad to merge it 😆

**Comment by NathanBeddoeWebDev** [comment]
Haha, all good. I'm not a massive open sourcer so I don't really mind. Sass performance has just been something of a quest for me at work for the past year.

**Pull request merged**
